### PR TITLE
Ajuste arquivo index.html sintaxe

### PR DESCRIPTION
**Pull request by hanelore**
Fixed the line 284 with correct phrase.

### CODE REVIEW

**Comment by guisantos** [comment]
Obrigado pela contribuição @hanelore !

**Comment by hanelore** [comment]
You are welcome @guisantos :)

**Comment by guisantos** [comment]
@hanelore can you give me your e-mail or twitter? I'd like to contact you.

**Comment by hanelore** [comment]
@guisantos e-mail sent with a escrow friend. I use Bitmessage.

Thanks again.

**Pull request merged**
